version: '3.8'

services:
  discord-music-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-music-bot
    restart: unless-stopped
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
    
    # Mount .env file for environment variables
    env_file:
      - .env
    
    # Volume mounts for persistent data
    volumes:
      - ./configs:/app/configs
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./discord_bot.log:/app/discord_bot.log
    
    # Network configuration
    networks:
      - discord-bot-network
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import discord; print('Bot OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  discord-bot-network:
    driver: bridge

# Optional: Add a monitoring service
# services:
#   watchtower:
#     image: containrrr/watchtower
#     container_name: watchtower
#     restart: unless-stopped
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     command: --interval 300 --cleanup discord-music-bot